const bcpaSchema = {
  sendformonly:{
    constants: {
      County: "Broward County",
    },
    formdata:{
      "Taxyear":"#changeTaxyearId"
    }, 
    function:"getformdata"
  },
  data: {
    tableSelectors: {
      folioNumberId: "#folioNumberId",
      ownerNameId: "#ownerNameId",
      ownerName2Id: "#ownerName2Id",
      mailingAddressId: "#mailingAddressId",
      updateMailingAddressId: "#updateMailingAddressId",
      situsAddressId: "#situsAddressId",
      neighborhood: "#neighborhood",
      useCodeId: "#useCodeId",
      millageCodeId: "#millageCodeId",
      bldgSqFTId: "#bldgSqFTId",
      buildingId: "#buildingId",
      bldgUnderAirFootageId: "#bldgUnderAirFootageId",
      effectiveAgeId: "#effectiveAgeId",
      actualAgeId: "#actualAgeId",
      unitsBedsBathsId: "#unitsBedsBathsId",
      deputyAppraiserNameId: "#deputyAppraiserNameId",
      phoneNumber: "#phoneNumber",
      email: "#email",
      legalDescId: "#legalDescId",
      historicDistrict: "#historicDistrict",

      //Property Assessment
      currentTaxYearId: "#currentTaxYearId",
      landCurrentYearId: "#landCurrentYearId",
      bldgCurrentYearId: "#bldgCurrentYearId",
      justOtherYearId: "#justOtherYearId",
      justCurrentYearId: "#justCurrentYearId",
      sohCurrentYearId: "#sohCurrentYearId",
      lastTaxYearId: "#lastTaxYearId",
      landLastYearId: "#landLastYearId",
      bldgLastYearId: "#bldgLastYearId",
      justOtherLastYearId: "#justOtherLastYearId",
      justLastYearId: "#justLastYearId",
      sohLastYearId: "#sohLastYearId",
      assessedLastYearId: "#assessedLastYearId",
      lastTwoTaxYearId: "#lastTwoTaxYearId",
      landLasttwoYearsId: "#landLasttwoYearsId",
      bldgLasttwoYearsId: "#bldgLasttwoYearsId",
      justOtherLastTwoYearsId: "#justOtherLastTwoYearsId",
      justLasttwoYearsId: "#justLasttwoYearsId",
      sohLasttwoYearsId: "#sohLasttwoYearsId",
      assessedLasttwoYearsId: "#assessedLasttwoYearsId",
      comSohYearId: "#comSohYearId",

      //Exemptions And Taxing Authority Information
      justValueCounty: "#justValueCounty",
      justValueSchoolBoard: "#justValueSchoolBoard",
      justValueMunicipal: "#justValueMunicipal",
      justValueIndependent: "#justValueIndependent",
      portabilityValueCounty: "#portabilityValueCounty",
      portabilityValueSchoolBoard: "#portabilityValueSchoolBoard",
      portabilityValueMunicipal: "#portabilityValueMunicipal",
      portabilityValueIndependent: "#portabilityValueIndependent",
      sohYearId: "#sohYearId",
      homesteadFlagId: "#homesteadFlagId",
      sohValueCounty: "#sohValueCounty",
      sohValueSchoolBoard: "#sohValueSchoolBoard",
      sohValueMunicipal: "#sohValueMunicipal",
      sohValueIndependent: "#sohValueIndependent",
      homesteadPercentId: "#homesteadPercentId",
      ncuPercentId: "#ncuPercentId",
      dpscId: "#dpscId",
      he1AmountCounty: "#he1AmountCounty",
      he1AmountSchoolBoard: "#he1AmountSchoolBoard",
      he1AmountMunicipal: "#he1AmountMunicipal",
      he1AmountIndependent: "#he1AmountIndependent",
      he2AmountCounty: "#he2AmountCounty",
      he2AmountSchoolBoard: "#he2AmountSchoolBoard",
      he2AmountMunicipal: "#he2AmountMunicipal",
      he2AmountIndependent: "#he2AmountIndependent",
      wvdAmountCounty: "#wvdAmountCounty",
      wvdAmountSchoolBoard: "#wvdAmountSchoolBoard",
      wvdAmountMunicipal: "#wvdAmountMunicipal",
      wvdAmountIndependent: "#wvdAmountIndependent",
      seniorExemptionCounty: "#seniorExemptionCounty",
      seniorExemptionMunicipal: "#seniorExemptionMunicipal",
      exemptionTypeId: "#exemptionTypeId",
      mexAmountCounty: "#mexAmountCounty",
      mexAmountSchoolBoard: "#mexAmountSchoolBoard",
      mexAmountMunicipal: "#mexAmountMunicipal",
      mexAmountIndependent: "#mexAmountIndependent",
      ahAmountCounty: "#ahAmountCounty",
      ahAmountSchoolBoard: "#ahAmountSchoolBoard",
      ahAmountMunicipal: "#ahAmountMunicipal",
      ahAmountIndependent: "#ahAmountIndependent",
      taxableAmountCounty: "#taxableAmountCounty",
      taxableAmountSchoolBoard: "#taxableAmountSchoolBoard",
      taxableAmountMunicipal: "#taxableAmountMunicipal",
      taxableAmountIndependent: "#taxableAmountIndependent",

      //Sales History For This Parcel
      lblBookAndPageId: "#lblBookAndPageId",
      salesHistoryDate1: "#salesHistoryDate1",
      salesHistoryDeedType1: "#salesHistoryDeedType1",
      salesQualification1: "#salesQualification1",
      salesHistoryPrice1: "#salesHistoryPrice1",
      bookAndPageOrCin1: "#bookAndPageOrCin1",
      salesHistoryDate2: "#salesHistoryDate2",
      salesHistoryDeedType2: "#salesHistoryDeedType2",
      salesQualification2: "#salesQualification2",
      salesHistoryPrice2: "#salesHistoryPrice2",
      bookAndPageOrCin2: "#bookAndPageOrCin2",
      salesHistoryDate3: "#salesHistoryDate3",
      salesHistoryDeedType3: "#salesHistoryDeedType3",
      salesQualification3: "#salesQualification3",
      salesHistoryPrice3: "#salesHistoryPrice3",
      bookAndPageOrCin3: "#bookAndPageOrCin3",
      salesHistoryDate4: "#salesHistoryDate4",
      salesHistoryDeedType4: "#salesHistoryDeedType4",
      salesQualification4: "#salesQualification4",
      salesHistoryPrice4: "#salesHistoryPrice4",
      bookAndPageOrCin4: "#bookAndPageOrCin4",
      salesHistoryDate5: "#salesHistoryDate5",
      salesHistoryDeedType5: "#salesHistoryDeedType5",
      salesQualification5: "#salesQualification5",
      salesHistoryPrice5: "#salesHistoryPrice5",
      bookAndPageOrCin5: "#bookAndPageOrCin5",

      //Recent Sales in This Subdivision
      recentSaleFolioNumber1: "#recentSaleFolioNumber1",
      recentSaleDate1: "#recentSaleDate1",
      recentSaleType1: "#recentSaleType1",
      recentSaleQualified1: "#recentSaleQualified1",
      recentSaleValue1: "#recentSaleValue1",
      recentSaleBookPageCin1: "#recentSaleBookPageCin1",
      recentSaleAddress1: "#recentSaleAddress1",
      recentSaleFolioNumber2: "#recentSaleFolioNumber2",
      recentSaleDate2: "#recentSaleDate2",
      recentSaleType2: "#recentSaleType2",
      recentSaleQualified2: "#recentSaleQualified2",
      recentSaleValue2: "#recentSaleValue2",
      recentSaleBookPageCin2: "#recentSaleBookPageCin2",
      recentSaleAddress2: "#recentSaleAddress2",
      recentSaleFolioNumber3: "#recentSaleFolioNumber3",
      recentSaleDate3: "#recentSaleDate3",
      recentSaleType3: "#recentSaleType3",
      recentSaleQualified3: "#recentSaleQualified3",
      recentSaleValue3: "#recentSaleValue3",
      recentSaleBookPageCin3: "#recentSaleBookPageCin3",
      recentSaleAddress3: "#recentSaleAddress3",
      recentSaleFolioNumber4: "#recentSaleFolioNumber4",
      recentSaleDate4: "#recentSaleDate4",
      recentSaleType4: "#recentSaleType4",
      recentSaleQualified4: "#recentSaleQualified4",
      recentSaleValue4: "#recentSaleValue4",
      recentSaleBookPageCin4: "#recentSaleBookPageCin4",
      recentSaleAddress4: "#recentSaleAddress4",
      recentSaleFolioNumber5: "#recentSaleFolioNumber5",
      recentSaleDate5: "#recentSaleDate5",
      recentSaleType5: "#recentSaleType5",
      recentSaleQualified5: "#recentSaleQualified5",
      recentSaleValue5: "#recentSaleValue5",
      recentSaleBookPageCin5: "#recentSaleBookPageCin5",
      recentSaleAddress5: "#recentSaleAddress5",

      landCalculationType1: "#landCalculationType1",
      landCalculationPrice1: "#landCalculationPrice1",
      landCalculationFactor1: "#landCalculationFactor1",
      landCalculationZoning: "#landCalculationZoning",
      landCalculationType2: "#landCalculationType2",
      landCalculationPrice2: "#landCalculationPrice2",
      landCalculationFactor2: "#landCalculationFactor2",
      landCalculationType3: "#landCalculationType3",
      landCalculationPrice3: "#landCalculationPrice3",
      landCalculationFactor3: "#landCalculationFactor3",
      landCalculationType4: "#landCalculationType4",
      landCalculationPrice4: "#landCalculationPrice4",
      landCalculationFactor4: "#landCalculationFactor4",

      // Special Assessments
      fireDistrict: "#fireDistrict",
      garbageDistrict: "#garbageDistrict",
      lightDistrict: "#lightDistrict",
      drainageDistrict: "#drainageDistrict",
      improvementDistrict: "#improvementDistrict",
      safeNeighborhoodDistrict: "#safeNeighborhoodDistrict",
      stormDistrict: "#stormDistrict",
      cleanDistrict: "#cleanDistrict",
      miscDistrict: "#miscDistrict",
      fireClass: "#fireClass",
      garbageClass: "#garbageClass",
      lightClass: "#lightClass",
      drainageClass: "#drainageClass",
      improvementClass: "#improvementClass",
      safeNeighborhoodClass: "#safeNeighborhoodClass",
      stormClass: "#stormClass",
      cleanClass: "#cleanClass",
      miscClass: "#miscClass",
      fireAssessment: "#fireAssessment",
      garbageAssessment: "#garbageAssessment",
      lightAssessment: "#lightAssessment",
      drainageAssessment: "#drainageAssessment",
      cBrow: "#cBrow",
      improvementAssessment: "#improvementAssessment",
      safeNeighborhoodAssessment: "#safeNeighborhoodAssessment",
      stormAssessment: "#stormAssessment",
      cleanAssessment: "#cleanAssessment",
      miscAssessment: "#miscAssessment",

      // Schools
      esName: "#esName",
      esGrade: "#esGrade",
      msName: "#msName",
      msGrade: "#msGrade",
      hsName: "#hsName",
      hsGrade: "#hsGrade",

      // Elected Officials
      propertyAppraiserNameId: "#propertyAppraiserNameId",
      countyCommissionDistrictId: "#countyCommissionDistrictId",
      countyCommissionNameId: "#countyCommissionNameId",
      usHouseRepDistrictId: "#usHouseRepDistrictId",
      usHouseRepNameId: "#usHouseRepNameId",
      floridaHouseRepDistrictId: "#floridaHouseRepDistrictId",
      floridaHouseRepNameId: "#floridaHouseRepNameId",
      floridaSenatorId: "#floridaSenatorId",
      floridaSenatorNameId: "#floridaSenatorNameId",
      SchoolBoardNameId: "#SchoolBoardNameId",
    },
    function: "getbyselectors",
  },
};

const miamidadeSchema = {
  exceptions:{
    function:"runmiamiexceptions"
  },
  propertyInformation: {
    constants: {
      County: "Miamidade County",
    },
    tableSelector: ".property_info table",
    tableType: "horizontal",
    ignoreRows: {
     indices:[0]
    },
    function: "getalldata",
  },
  assessmentInfo: {
    tableSelector: ".assessment-info-table table",
    tableType: "matrix",
    ignoreRows: {
      indices:[0]
    },
    function: "getalldata",
  },

  legalDescription:{
    tableSelector:"pa-legaldescription div table",
    tableType:"vertical",
    function:"getalldata"
  },
  salesInformation: {
    tableSelector: "pa-salesinforamtion div table",
    tableType: "vertical",
    ignoreRows: {
      indices:[0]
    },
    function: "getalldata",
  },
  landInformation: {
    tableSelector: "pa-landinformation div table",
    tableType: "vertical",
    ignoreRows: {
      indices:[0]
    },
    function: "getalldata",
  },
  benefitsInformation: {
    tableSelector: "pa-benefitsinformation div table",
    tableType: "matrix",
    ignoreRows: {
      values: ["benefits information","Note: Not all benefits are applicable to all Taxable Values (i.e. County, School Board, City, Regional)."],
      columns: [0],
      caseSensitive: false
    },
    function: "getalldata",
  },
  buildingInformation: {
    tableSelector: "pa-buildinginformation div table",
    tableType: "vertical",
    ignoreRows: {
      indices:[0]
    },
    function: "getalldata",
  },
  extraFeatures: {
    tableSelector: "pa-extrafeatures div table",
    tableType: "vertical",
    ignoreRows: {
      indices:[0]
    },
    function: "getalldata",
  },
};

const paopropterySchema = {
  proptertyDetail: {
    constants: {
      County: "Duval County",
    },
    tableSelector: "#propDetail_data table",
    tableType: "horizontal",
    function: "getalldata",
  },
  propValue: {
    tableSelector: "#propValue table",
    tableType: "matrix",
    function: "getalldata",
  },
  detailHistory: {
    tableSelector: "#tl00_cphBody_gridSalesHistory",
    tableType: "vertical",
    functino: "getalldata",
  },
  landLegal: {
    tableSelector: "#ctl00_cphBody_gridLand",
    tableType: "vertical",
    function: "getalldata",
  },
  legal: {
    tableSelector: "#ctl00_cphBody_gridLegal",
    tableType: "vertical",
    function: "getalldata",
  },
  taxDetails: {
    tableSelector: "#ctl00_cphBody_gridTaxDetails",
    tableType: "matrix",
    ignoreRows: {
      values: ["Totals"],
      columns: [3]
    },
    function: "getalldata",
  },
  yearTax: {
    tableSelector: "#details_trimExtended table",
    tableType: "matrix",
    function: "getalldata",
  },
};
const collierSchema = {
  data: {
    constants: {
      County: "Collier County",
    },
    tableSelectors: {
      ParcelID: "#ParcelID",
      FullAddressUnit: "#FullAddressUnit",
      GOOGLE_LINK: "#GOOGLE_LINK",
      StreetCity: "#StreetCity",
      StreetZone: "#StreetZone",
      Name1: "#Name1",
      Name2: "#Name2",
      Name3: "#Name3",
      Name4: "#Name4",
      Name5: "#Name5",
      CityCountry: "#CityCountry",
      City: "#City",
      StateProv: "#StateProv",
      State: "#State",
      ZipCode: "#ZipCode",
      USZip: "#USZip",
      MapNumber: "#MapNumber",
      StrapNumber: "#StrapNumber",
      Section: "#Section",
      Township: "#Township",
      Range: "#Range",
      TotalAcres: "#TotalAcres",
      Legal: "#Legal",
      MillageArea: "#MillageArea",
      scDescription: "#scDescription",
      ucDescription: "#ucDescription",
      School: "#School",
      Other: "#Other",
      Total: "#Total",
      SaleDate1: "#SaleDate1",
      SaleAmount1: "#SaleAmount1",
      SaleDate2: "#SaleDate2",
      SaleAmount2: "#SaleAmount2",
      SaleDate3: "#SaleDate3",
      SaleAmount3: "#SaleAmount3",
      SaleDate4: "#SaleDate4",
      SaleAmount4: "#SaleAmount4",
      SaleDate5: "#SaleDate5",
      SaleAmount5: "#SaleAmount5",
      ROLLTYPE: "#ROLLTYPE",
      LandAssessedAmount: "#LandAssessedAmount",
      ImprovementsAssessedAmt: "#ImprovementsAssessedAmt",
      TotalJustAmount: "#TotalJustAmount",
      SOHAssessmentReduction: "#SOHAssessmentReduction",
      "10PCTAssessmentReduction": "#10PCTAssessmentReduction",
      AGAssessmentReduction: "#AGAssessmentReduction",
      AssessedAmount: "#AssessedAmount",
      HMSTDExemptAmount: "#HMSTDExemptAmount",
      WIDOWExemptAmount: "#WIDOWExemptAmount",
      CIVExemptAmount: "#CIVExemptAmount",
      VETExemptAmount: "#VETExemptAmount",
      BLINDExemptAmount: "#BLINDExemptAmount",
      DISABLEDExemptDesc: "#DISABLEDExemptDesc",
      DISABLEDExemptAmount: "#DISABLEDExemptAmount",
      GrossSchooltaxvalue: "#GrossSchooltaxvalue",
      ADDHMSTDExemptAmount: "#ADDHMSTDExemptAmount",
      SENIORExemptAmount: "#SENIORExemptAmount",
      LTSENIORExemptAmount: "#LTSENIORExemptAmount",
      GrossTaxableAmount: "#GrossTaxableAmount",
      DISABLEVETExemptAmountpct: "#DISABLEVETExemptAmountpct",
      DEPLOYEDExemptAmountpct: "#DEPLOYEDExemptAmountpct",
      AFDHSGExemptAmountpct: "#AFDHSGExemptAmountpct",
      Schooltaxvalue: "#Schooltaxvalue",
      TaxableAmount: "#TaxableAmount",
      TOTALADVTAXES: "#TOTALADVTAXES",
      TOTALNADVTAXES: "#TOTALNADVTAXES",
      TOTALTAXES: "#TOTALTAXES",
      taxyear1: "#taxyear1",
      issuer1: "#issuer1",
      permitno1: "#permitno1",
      codate1: "#codate1",
      tempcodate1: "#tempcodate1",
      finalbldgdate1: "#finalbldgdate1",
      permittype1: "#permittype1",
      taxyear2: "#taxyear2",
      issuer2: "#issuer2",
      permitno2: "#permitno2",
      codate2: "#codate2",
      tempcodate2: "#tempcodate2",
      finalbldgdate2: "#finalbldgdate2",
      permittype2: "#permittype2",
      SEQNO1: "#SEQNO1",
      CALCCODE1: "#CALCCODE1",
      TOTALUNITS1: "#TOTALUNITS1",
      YRBUILT1: "#YRBUILT1",
      BLDGCLASS1: "#BLDGCLASS1",
      BASEAREA1: "#BASEAREA1",
      TYADJAREA1: "#TYADJAREA1",
      ParcelID3: "#ParcelID3",
      FullAddressUnit3: "#FullAddressUnit3",
      GOOGLE_LINK3: "#GOOGLE_LINK3",
      StreetCity3: "#StreetCity3",
      StreetZone3: "#StreetZone3",
      message: "#message",
    },
    function: "getbyselectors",
  },
};


